// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGF1v5tOHQ2g0hobwZ4PUP49TYy_EtQIE',
    appId: '1:825678721854:web:04cdb1e28c1c4ef3d7f26f',
    messagingSenderId: '825678721854',
    projectId: 'socialnetworkapp-2ece8',
    authDomain: 'socialnetworkapp-2ece8.firebaseapp.com',
    storageBucket: 'socialnetworkapp-2ece8.appspot.com',
    measurementId: 'G-XBTEPGSDY3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS4pd-ROhqifQfgBovzJXpPrhrGNdL6hw',
    appId: '1:825678721854:android:4ce90f98e29f8556d7f26f',
    messagingSenderId: '825678721854',
    projectId: 'socialnetworkapp-2ece8',
    storageBucket: 'socialnetworkapp-2ece8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWREEKW-eutStWzqViLAOrf5VbHaAWjBE',
    appId: '1:825678721854:ios:0c5aee1b03569285d7f26f',
    messagingSenderId: '825678721854',
    projectId: 'socialnetworkapp-2ece8',
    storageBucket: 'socialnetworkapp-2ece8.appspot.com',
    androidClientId: '825678721854-odiesonc1rdftr6qk7acpvk5eqolfrig.apps.googleusercontent.com',
    iosClientId: '825678721854-5ke495q88cknkkr8fhbc3i4tvrmtnha2.apps.googleusercontent.com',
    iosBundleId: 'vn.socialnetwork.socialnetworkapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWREEKW-eutStWzqViLAOrf5VbHaAWjBE',
    appId: '1:825678721854:ios:aab1981827938002d7f26f',
    messagingSenderId: '825678721854',
    projectId: 'socialnetworkapp-2ece8',
    storageBucket: 'socialnetworkapp-2ece8.appspot.com',
    androidClientId: '825678721854-odiesonc1rdftr6qk7acpvk5eqolfrig.apps.googleusercontent.com',
    iosClientId: '825678721854-fvrj9mealutkm8lb3tfnha6852s6oof4.apps.googleusercontent.com',
    iosBundleId: 'vn.socialnetwork.socialnetworkapp.RunnerTests',
  );
}
